### ISSUE TITLE
Improve the style 

### ISSUE THREAD

**Issue by tansuluu** [tansuluu/Opentravel#192]
Please make the size of icons(likes,view,comment) more bigger, in blogs page 
![Screenshot_2019-04-21 Single Blog](https://user-images.githubusercontent.com/26306921/56467650-7761df00-6443-11e9-9bc8-c232820a58c7.png)

**Comment by ElmiraKurmanbekova** [comment]
I have done

**Comment by tansuluu** [comment]
Thanks @ElmiraKurmanbekova
